import { useState, useEffect } from 'react'
import { Activity, AlertTriangle, CalendarDays, ClipboardCheck, FileText, FolderOpen, Gauge, Target, Upload } from 'lucide-react'
import ActivityItem from '../components/ActivityItem'
import PageTitle from '../components/PageTitle'
import Stat from '../components/Stat'
import { formatDate, greetingFor, pct, rupiah } from '../utils/format'

function Dashboard({ programs, docs, events, overall, totalPagu, totalRealisasi, onNavigate, currentUnit, onUnitFilterChange, unitFilterOptions }) {
  const [now, setNow] = useState(() => new Date())
  useEffect(() => {
    const timer = setInterval(() => setNow(new Date()), 1000)
    return () => clearInterval(timer)
  }, [])
  const monthEvents = events.filter(e => e.date.startsWith('2026-09'))
  return <><PageTitle eyebrow={`Ringkasan kinerja · ${formatDate(now)}`} title={greetingFor(now.getHours())}><div className="title-actions-inline"><p className="subtitle">Pantau perencanaan dan kinerja Kecamatan Kedungwaringin dalam satu tempat.</p><label className="filter-select-wrap"><span>Unit</span><select value={currentUnit} onChange={e => onUnitFilterChange(e.target.value)}>{unitFilterOptions.map(option => <option key={option} value={option}>{option}</option>)}</select></label></div></PageTitle>
    <div className="stat-grid"><Stat label="Realisasi anggaran" value={rupiah(totalRealisasi * 10000000)} note={currentUnit === 'Semua Unit' ? '▲ 8,4% dari bulan lalu' : `Unit: ${currentUnit}`} icon={Gauge}/><Stat label="Progress kinerja" value={`${overall}%`} note={currentUnit === 'Semua Unit' ? 'Dari seluruh program' : `Dari ${programs.length} program aktif`} icon={Target} tone="blue"/><Stat label="Program berjalan" value={programs.filter(p => p.status === 'Berjalan').length} note={`${programs.filter(p => p.status === 'Perlu perhatian').length} perlu perhatian`} icon={Activity} tone="orange"/><Stat label="Dokumen masuk" value={docs.length} note={`${docs.filter(d => d.status === 'Menunggu verifikasi').length} menunggu verifikasi`} icon={FolderOpen} tone="purple"/></div>
    <div className="dashboard-grid"><section className="card performance-card"><div className="card-head"><div><h2>Ikhtisar kinerja program</h2><p>Perbandingan target dan realisasi tahun anggaran 2026</p></div><button className="link-btn" onClick={() => onNavigate('pengendalian')}>Lihat detail <span>→</span></button></div><div className="chart"><div className="y-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="bars">{programs.map(p => <div className="bar-group" key={p.id}><div className="bar-wrap"><div className="bar target" style={{height: `${Math.min(100, pct(p.target, p.target))}%`}}/><div className="bar actual" style={{height: `${Math.min(100, pct(p.realisasi, p.target))}%`}}/></div><span>{p.kode}</span></div>)}</div><div className="legend"><span><i className="legend-target"/>Target</span><span><i className="legend-actual"/>Realisasi</span></div></div></section><section className="card warning-card"><div className="card-head"><div><h2>Early warning</h2><p>Perlu ditindaklanjuti minggu ini</p></div><AlertTriangle className="warning-icon" size={21}/></div><div className="warnings">{programs.filter(p => p.status === 'Perlu perhatian').map(p => <div className="warning-item" key={p.id}><div className="warning-dot"/><div><b>{p.nama}</b><small>Realisasi {pct(p.realisasi, p.target)}% · Batas {new Date(p.deadline).toLocaleDateString('id-ID', { day: '2-digit', month: 'short' })}</small></div><button onClick={() => onNavigate('pengendalian')}>Tindak</button></div>)}<div className="warning-item info"><div className="warning-dot blue"/><div><b>1 dokumen menunggu verifikasi</b><small>Laporan Realisasi Triwulan II.xlsx</small></div><button onClick={() => onNavigate('evaluasi')}>Review</button></div></div></section></div>
    <div className="dashboard-grid lower"><section className="card"><div className="card-head"><div><h2>Agenda terdekat</h2><p>Jadwal kegiatan dan tenggat pelaporan</p></div><CalendarDays size={20} className="muted-icon"/></div><div className="agenda">{monthEvents.map(e => <div className="agenda-row" key={e.date}><div className="date-box"><b>{new Date(e.date).getDate()}</b><small>SEP</small></div><div><b>{e.title}</b><small>{e.type} · Kecamatan Kedungwaringin</small></div><span className={`tag ${e.type === 'Deadline' ? 'orange' : ''}`}>{e.type}</span></div>)}</div></section><section className="card activity-card"><div className="card-head"><div><h2>Aktivitas terbaru</h2><p>Jejak perubahan terakhir di sistem</p></div><button className="link-btn" onClick={() => onNavigate('unduhan')}>Semua aktivitas →</button></div><div className="timeline"><ActivityItem icon={Upload} title="Laporan Realisasi Triwulan II.xlsx" text="diunggah oleh Admin" time="2 jam lalu"/><ActivityItem icon={ClipboardCheck} title="PRG-003 ditandai selesai" text="oleh Camat/Sekcam" time="Kemarin"/><ActivityItem icon={FileText} title="Rencana Kerja Kecamatan 2026.pdf" text="terverifikasi" time="2 hari lalu"/></div></section></div>
  </>
}

export default Dashboard
